"""empty message

Revision ID: 1e2e2ed522da
Revises: d78a33cca55a
Create Date: 2016-10-18 10:45:55.315831

"""

# revision identifiers, used by Alembic.
revision = '1e2e2ed522da'
down_revision = 'd78a33cca55a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    #op.drop_column('market', 'itemtype')
    with op.batch_alter_table("market") as batch_op:
        batch_op.drop_column('itemtype')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market', sa.Column('itemtype', sa.VARCHAR(), nullable=False))
    ### end Alembic commands ###
