"""empty message

Revision ID: 25bc9f6f612d
Revises: 1e2e2ed522da
Create Date: 2016-10-18 10:50:29.248641

"""

# revision identifiers, used by Alembic.
revision = '25bc9f6f612d'
down_revision = '1e2e2ed522da'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market', sa.Column('itemtype', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('market', 'itemtype')
    ### end Alembic commands ###
