"""empty message

Revision ID: 2afcafd1f4a5
Revises: None
Create Date: 2016-09-29 19:39:40.522709

"""

# revision identifiers, used by Alembic.
revision = '2afcafd1f4a5'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phonenumber', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('entrydate', sa.Date(), nullable=False),
    sa.Column('graddate', sa.Date(), nullable=False),
    sa.Column('school', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile')
    op.drop_table('users')
    ### end Alembic commands ###
