"""empty message

Revision ID: 46a337398655
Revises: 45ab1fea9b37
Create Date: 2016-10-03 23:36:30.719277

"""

# revision identifiers, used by Alembic.
revision = '46a337398655'
down_revision = '45ab1fea9b37'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event',)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'event', 'profile', ['school'], ['school'])
    ### end Alembic commands ###
