"""empty message

Revision ID: 5a7dffef742e
Revises: d648ddda5c4e
Create Date: 2016-10-14 14:52:37.137620

"""

# revision identifiers, used by Alembic.
revision = '5a7dffef742e'
down_revision = 'd648ddda5c4e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('postcomment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('commentor', sa.String(), nullable=True),
    sa.Column('pulseonwer', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('pulse', sa.Column('poster', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pulse', 'poster')
    op.drop_table('postcomment')
    ### end Alembic commands ###
