"""empty message

Revision ID: 6713e3cfa637
Revises: f080c7db571e
Create Date: 2016-10-17 13:05:21.604775

"""

# revision identifiers, used by Alembic.
revision = '6713e3cfa637'
down_revision = 'f080c7db571e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    #op.drop_column('event', 'price')
    with op.batch_alter_table("event") as batch_op:
        batch_op.drop_column('price')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('price', sa.VARCHAR(), nullable=False))
    ### end Alembic commands ###
