"""empty message

Revision ID: 672e659e10a6
Revises: 132e4b7d1464
Create Date: 2016-10-07 21:49:43.768642

"""

# revision identifiers, used by Alembic.
revision = '672e659e10a6'
down_revision = '132e4b7d1464'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('free', sa.Boolean(), nullable=True))
    op.add_column('event', sa.Column('imagename', sa.String(), nullable=True))
    op.add_column('market', sa.Column('free', sa.Boolean(), nullable=True))
    op.add_column('market', sa.Column('imagename', sa.String(), nullable=True))
    op.add_column('market', sa.Column('school', sa.String(), nullable=True))
    op.drop_column('market', 'time')
    op.drop_column('market', 'date')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market', sa.Column('date', sa.DATE(), nullable=False))
    op.add_column('market', sa.Column('time', sa.TIME(), nullable=False))
    op.drop_column('market', 'school')
    op.drop_column('market', 'imagename')
    op.drop_column('market', 'free')
    op.drop_column('event', 'imagename')
    op.drop_column('event', 'free')
    ### end Alembic commands ###
