"""empty message

Revision ID: 849e2641783b
Revises: a1c46137f040
Create Date: 2016-10-22 18:07:36.476501

"""

# revision identifiers, used by Alembic.
revision = '849e2641783b'
down_revision = 'a1c46137f040'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pulselikes', sa.Column('likes', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pulselikes', 'likes')
    ### end Alembic commands ###
