"""empty message

Revision ID: a1c46137f040
Revises: 25bc9f6f612d
Create Date: 2016-10-20 11:45:11.672111

"""

# revision identifiers, used by Alembic.
revision = 'a1c46137f040'
down_revision = '25bc9f6f612d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pulselikes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pulseonwer', sa.Integer(), nullable=True),
    sa.Column('likers', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pulselikes')
    ### end Alembic commands ###
