"""empty message

Revision ID: af5447823181
Revises: 9bac211ab692
Create Date: 2016-10-03 21:06:56.111399

"""

# revision identifiers, used by Alembic.
revision = 'af5447823181'
down_revision = '9bac211ab692'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('itemname', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('itemtype', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('school', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['school'], ['profile.school'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('market')
    ### end Alembic commands ###
