"""empty message

Revision ID: c403b4f0fa98
Revises: None
Create Date: 2016-10-03 23:54:11.247820

"""

# revision identifiers, used by Alembic.
revision = 'c403b4f0fa98'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eventtitle', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('price', sa.String(), nullable=False),
    sa.Column('eventtype', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('eventvenue', sa.String(), nullable=False),
    sa.Column('eventoption', sa.Boolean(), nullable=True),
    sa.Column('school', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phonenumber', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('entrydate', sa.Date(), nullable=False),
    sa.Column('graddate', sa.Date(), nullable=False),
    sa.Column('school', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('itemname', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('itemtype', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('school', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['school'], ['profile.school'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('market')
    op.drop_table('profile')
    op.drop_table('users')
    op.drop_table('event')
    ### end Alembic commands ###
