"""empty message

Revision ID: d648ddda5c4e
Revises: 8651e4922601
Create Date: 2016-10-14 14:13:45.275306

"""

# revision identifiers, used by Alembic.
revision = 'd648ddda5c4e'
down_revision = '8651e4922601'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pulse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post', sa.String(), nullable=True),
    sa.Column('school', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pulse')
    ### end Alembic commands ###
