"""empty message

Revision ID: f080c7db571e
Revises: 5a7dffef742e
Create Date: 2016-10-17 11:15:23.617617

"""

# revision identifiers, used by Alembic.
revision = 'f080c7db571e'
down_revision = '5a7dffef742e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('Eventposter', sa.String(), nullable=True))
    op.add_column('market', sa.Column('seller', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('market', 'seller')
    op.drop_column('event', 'Eventposter')
    ### end Alembic commands ###
